# Generated by Django 4.0.4 on 2022-06-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.IntegerField(unique=True)),
                ('medicine', models.CharField(max_length=100, verbose_name='Product')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('active', models.BooleanField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date_ingress', models.DateField()),
                ('date_expiration', models.DateField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.product')),
            ],
        ),
        migrations.CreateModel(
            name='Provider_medicines',
            fields=[
                ('medicine_provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('price_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.product')),
            ],
        ),
    ]
