# Generated by Django 4.0.4 on 2022-06-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_medicines',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
