# Generated by Django 4.0.4 on 2022-06-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_provider_medicines_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider_medicines',
            new_name='Provider_medicine',
        ),
    ]
