# Generated by Django 4.0.4 on 2022-06-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_rename_provider_medicines_provider_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider_medicine',
            name='provider',
            field=models.IntegerField(unique=True),
        ),
    ]
